image: docker:19.03.12

stages:
  - build
  - deploy

variables:
  CONTAINER_NAME: slack-service
  ENVIROMENT: staging

build:
  stage: build
  script:
    - echo $DOCKER_HUB_ID
    - docker login -u $DOCKER_HUB_ID -p $DOCKER_HUB_PASSWORD
    - docker build -t $DOCKER_HUB_ID/$IMAGE_NAME .
    - docker push $DOCKER_HUB_ID/$IMAGE_NAME
  environment:
    name: $ENVIROMENT

deploy:
  stage: deploy
  script:
    - apk upgrade && apk update
    - apk add openssh-client
    - apk add sshpass
    - sshpass -p "$USER_PASSWORD" ssh -o StrictHostKeyChecking=no $USER_ID@$STAGING_SERVER docker pull $DOCKER_HUB_ID/$IMAGE_NAME
    - sshpass -p "$USER_PASSWORD" ssh -o StrictHostKeyChecking=no $USER_ID@$STAGING_SERVER "docker stop $CONTAINER_NAME || true"
    - sshpass -p "$USER_PASSWORD" ssh -o StrictHostKeyChecking=no $USER_ID@$STAGING_SERVER docker run --rm -d -p 80:8080 --net kafka-docker_ai-networks --name $CONTAINER_NAME $DOCKER_HUB_ID/$IMAGE_NAME
  environment:
    name: $ENVIROMENT
    url: $STAGING_SERVER
