server:
  port: 30001

spring:
  application:
    name: slack-service
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

kafka:
  bootstrap:
    servers: 139.150.75.240:9092
