server:
  port: 30010

eureka:
  instance:
    prefer-ip-address: true
    ip-address: "${HOST_IP}"

spring:
  application:
    name: slack-service

springfox:
  documentation:
    swagger:
      v2:
        path: /email-service/v2/api-docs


management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh