server:
  port: 30010

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 139.150.75.239

spring:
  application:
    name: slack-service

kafka:
  bootstrap:
    servers: 10.7.27.17:9092

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh